
@scheme = https
@ades = test.eodatahub.org.uk/ades

@deployStatus = {{deployProcessJson.response.headers.Location}}

@processName = get-asset-impact-workflow-fileupload

###
# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/{{processName}} HTTP/1.1
Authorization: Bearer {{token}}


###
# @name listprocesses

GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json


###

# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "executionUnit": {
    "href": "https://gist.githubusercontent.com/geodowd/1776c94ac067989a1222e457c023abb9/raw/5167571e13c0739739f233e43ccd4e376bfdac3a/get_asset_impact.cwl",
    "type": "application/cwl"
  }
}




###
# @name processdetails

GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/{{processName}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

